[tool.poetry]
name = "detection-eng-llm"
version = "0.1.0"
description = ""
authors = ["Caio Ferreira"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
