[tool.poetry]
name = "detection-eng-llm"
version = "0.1.0"
description = ""
authors = ["Caio Ferreira"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.40.2"
dspy = "^2.5.41"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
